export const R2_BUCKET_URL =
  'https://pub-bf7510c355ec46498ff4a9278d7350fb.r2.dev'

export const PAGES = [
  {
    label: 'Sobre',
    href: '/sobre',
  },
  {
    label: 'Serviços',
    href: '/servicos',
  },
  {
    label: 'Vagas',
    href: '/vagas',
  },
  {
    label: 'Portfólio',
    href: '/portfolio',
  },
  {
    label: 'Blog',
    href: '/blog',
  },
]

export const SOCIAL = [
  {
    label: 'Instagram',
    href: 'https://www.instagram.com/linkjrcastanhal',
  },
  {
    label: 'Linkedin',
    href: 'https://www.linkedin.com/company/linkjr/',
  },
  {
    label: 'Github',
    href: 'https://github.com/linkjr-castanhal',
  },
]

export const TEAM = [
  {
    firstName: 'Yomara',
    lastName: 'Pires',
    role: 'Docente conselheira',
    type: 'teacher',
    linkedin: 'yomara-pires-38206699',
    lattes: '5304797342599931',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Bruno',
    lastName: 'Lyra',
    role: 'Docente conselheiro',
    type: 'teacher',
    linkedin: 'brunolyra2111',
    lattes: '1897829604434609',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Adailton',
    lastName: 'Lima',
    role: 'Docente conselheiro',
    type: 'teacher',
    linkedin: 'adailtonmlima',
    lattes: '3179032920191179',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Karol',
    lastName: 'Wojtyla',
    role: 'Presidente',
    type: 'student',
    linkedin: 'karolwojtyla',
    github: 'kwojtyla',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Alícia',
    lastName: 'Maia',
    role: 'Vice-presidente',
    type: 'student',
    linkedin: 'dev-maia',
    github: 'Ali-Maia',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Aridan',
    lastName: 'Pantoja',
    role: 'Diretor de Projetos',
    type: 'student',
    linkedin: 'aridanpantoja',
    github: 'aridanpantoja',
    image: `${R2_BUCKET_URL}/aridan-pantoja.webp`,
  },
  {
    firstName: 'Ítalo',
    lastName: 'Melo',
    role: 'Diretor Financeiro',
    type: 'student',
    linkedin: 'ítalo-melojsm',
    github: '',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Linda',
    lastName: 'Nowaczyk',
    role: 'Diretora de Marketing',
    type: 'student',
    linkedin: 'lindanowaczyk',
    github: 'lindanowaczyk',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Beatriz',
    lastName: 'Abreu',
    role: 'Diretora de Pessoas & Desempenho',
    type: 'student',
    linkedin: 'beatriz-abreu-aa776a273',
    github: 'beare-Beatriz',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Sarah',
    lastName: 'Cabral',
    role: 'Diretora de UX/UI',
    type: 'student',
    linkedin: 'bysarahcabral',
    github: 'bysarahcabral',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Edson',
    lastName: 'Costa',
    role: 'Engenheiro de Software',
    type: 'student',
    linkedin: 'edsoncostadev',
    github: 'ecsistem',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'João',
    lastName: 'Medeiros',
    role: 'Engenheiro de Front-End',
    type: 'student',
    linkedin: 'dev-joao-medeiros',
    github: 'medeiros20',
    image: `${R2_BUCKET_URL}/joao-medeiros.webp`,
  },
  {
    firstName: 'Pedro',
    lastName: 'Porpino',
    role: 'Engenheiro de Front-End',
    type: 'student',
    linkedin: 'pedro-augusto-38825224b',
    github: 'pedrozxx',
    image: `${R2_BUCKET_URL}/pedro-porpino.webp`,
  },
  {
    firstName: 'Italo',
    lastName: 'Souza',
    role: 'Engenheiro de Back-End',
    type: 'student',
    linkedin: 'silvaitalo',
    github: 'italossilva',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Nycolas',
    lastName: 'Bastos',
    role: 'Engenheiro de Dados',
    type: 'student',
    linkedin: 'nycolas-bastos-dataengineer',
    github: 'TrInfra',
    image: `${R2_BUCKET_URL}/nycolas-bastos.webp`,
  },
  {
    firstName: 'Gustavo',
    lastName: 'Nunes',
    role: 'Engenheiro de Dados',
    type: 'student',
    linkedin: 'gustavo-nunes-data-engineer',
    github: 'gustavon10',
    image: `${R2_BUCKET_URL}/gustavo-nunes.webp`,
  },
  {
    firstName: 'Leandro',
    lastName: 'Félix',
    role: 'Product Designer',
    type: 'student',
    linkedin: 'leandrofelixx',
    github: 'felixxleandro',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Éfran',
    lastName: 'Sousa',
    role: 'Analista administrativo',
    type: 'student',
    linkedin: 'dev-efran-sousa',
    github: 'Efran-Sousa',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
  {
    firstName: 'Rafael',
    lastName: 'Lopes',
    role: 'Analista de Pessoas & Desempenho',
    type: 'student',
    linkedin: 'rafael-lopes-moraes-688138254',
    image: `${R2_BUCKET_URL}/karol-wojtyla.webp`,
  },
]

export const siteConfig = {
  name: 'LinkJr',
  url: 'https://linkjr.com.br',
  description: 'Conectando ideias, Impulsionando soluções',
  ogImage: '/og.jpg',
}
